export const EDEN_REPORT_ENTRY_CONFIG = [
    { id: 'consultas-monthly-template', name: 'RM Consultas Externas'}, 
    { id: 'ccd-monthly-template', name: 'RM CCD'}, 
    { id: 'malaria-monthly-template', name: 'RM Malária'}, 
    { id: 'saaj-monthly-template', name: 'RM SAAJ'},
    { id: 'balancete-monthly-template', name: 'Requisição/Balancete'}, 
    { id: 'pharmacy-cash-monthly-template', name: 'Mapa de Caixa'},
    { id: 'nutrition-monthly-template', name: 'RM Nutrição'},
    { id: 'tda-1-monthly-template', name: 'RM TDA 1'}, 
    { id: 'tda-2-monthly-template', name: 'RM TDA 2'},
    { id: "tdi-monthly-template", name: "RM TDI"},
    { id: 'ats-monthly-template', name: 'RM ATS'}, 
    { id: 'hiv-sida-monthly-template', name: 'RM HIV/SIDA'}, 
    { id: 'prep-monthly-template', name: 'RM PrEP'}, 
    { id: 'dah-monthly-template', name: 'RM DAH'}, 
    { id: 'its-monthly-template', name: 'RM ITS'}, 
    { id: 'apss-pp-quartely-template', name: 'RT APSS/PP'},
    { id: 'pnct-provisorio-template', name: 'PNCT Provisório'}, 
    { id: 'pctc-01a-template', name: 'PNCT 01A'}, 
    { id: 'pnct-07-template', name: 'PNCT 07'}, 
    { id: 'pnct-ic-10a-template', name: 'PNCT IC-10A'}, 
    { id: 'pnct-r05-template', name: 'PNCT R05'}, 
    { id: 'pnct-r06-template', name: 'PNCT R06'}, 
    { id: 'pnct-r07-template', name: 'PNCT R07'}, 
    { id: 'pnct-08-template', name: 'PNCT 08'}, 
    { id: 'pnct-09-template', name: 'PNCT 09'}, 
    { id: 'pnct-11a-template', name: 'PNCT APSS 11A'}, 
    { id: 'pnct-12-template', name: 'PNCT 12'}, 
    { id: 'pnct-14d-template', name: 'PNCT 14D'}
];
