export const EDEN_REPORTS = [
    { id: 'consultas', name: 'RM Consultas Externas'}, 
    { id: 'ccd', name: 'RM CCD'}, 
    { id: 'malaria', name: 'RM Malária'}, 
    { id: 'saaj', name: 'RM SAAJ'},
    { id: 'balancete', name: 'Requisição/Balancete'}, 
    { id: 'pharmacy-cash', name: 'Mapa de Caixa'},
    { id: 'nutrition', name: 'RM Nutrição'},
    { id: 'tda-1', name: 'RM TDA 1'}, 
    { id: 'tda-2', name: 'RM TDA 2'},
    { id: "tdi", name: "RM TDI"},
    { id: 'ats', name: 'RM ATS'}, 
    { id: 'hiv-sida', name: 'RM HIV/SIDA'}, 
    { id: 'prep', name: 'RM PrEP'}, 
    { id: 'dah', name: 'RM DAH'}, 
    { id: 'its', name: 'RM ITS'}, 
    { id: 'apss-pp', name: 'RT APSS/PP'},
    { id: 'pnct-provisorio', name: 'PNCT Provisório'}, 
    { id: 'pctc-01a', name: 'PNCT 01A'}, 
    { id: 'pnct-07', name: 'PNCT 07'}, 
    { id: 'pnct-ic-10a', name: 'PNCT IC-10A'}, 
    { id: 'pnct-r05', name: 'PNCT R05'}, 
    { id: 'pnct-r06', name: 'PNCT R06'}, 
    { id: 'pnct-r07', name: 'PNCT R07'}, 
    { id: 'pnct-08', name: 'PNCT 08'}, 
    { id: 'pnct-09', name: 'PNCT 09'}, 
    { id: 'pnct-11a', name: 'PNCT APSS 11A'}, 
    { id: 'pnct-12', name: 'PNCT 12'}, 
    { id: 'pnct-14d', name: 'PNCT 14D'}
];
