export const TES_CMAM_MEDICATIONS = [

  { fnm: "2-D-1", name: "Bisacodil 5 mg Comp." },
  { fnm: "2-D-3", name: "Glicerina 1,5 g Sup." },
  { fnm: "2-I-2", name: "Anti-hemorroidário 30 g Sup." },
  { fnm: "3-A-1", name: "Dexametasona 4 mg/mL Inj." },
  { fnm: "3-A-3", name: "Hidrocortisona 100 mg Inj." },
  { fnm: "3-A-4", name: "Prednisolona 5 mg Comp." },
  { fnm: "3-A-5", name: "Prednisolona 20 mg Comp." },
  { fnm: "3-A-6", name: "Prednisolona 50 mg/10 ml Inj." },
  { fnm: "3-B-2", name: "Glibenclamida 5 mg Comp." },
  { fnm: "3-B-4", name: "Metformina 500 mg Comp." },
  { fnm: "3-B-7", name: "Insulina de acção curta (rápida) 100 U.I/mL Inj." },
  { fnm: "4-A-3", name: "Clotrimazol 100 mg Óvulo vaginal" },
  { fnm: "4-A-8", name: "Nistatina 100 000 U.I Comp. vaginal" },
  { fnm: "4-B-3", name: "Metilergometrina 0,125 mg Comp." },
  { fnm: "4-B-4", name: "Misoprostol 200 µg Comp." },
  { fnm: "4-B-5", name: "Oxitocina 5 U.I./mL Inj." },
  { fnm: "4-B-5", name: "Glicerina 3 g Sup." },
  { fnm: "4-B-6", name: "Terbutalina 2,5 mg Comp." },
  { fnm: "4-B-7", name: "Sulfato de Magnésio a 10% 100 mg/mL Inj." },
  { fnm: "4-F-3", name: "Etinilestradioli e Levonorgestrel (Microgynon) 30 µg + 150 µg" },
  { fnm: "4-F-6", name: "Levonorgestrel (Microlut) 30 µg Comp." },
  { fnm: "4-F-7", name: "Medroxiprogesterona (Depoprovera) 150 mg/mL Inj." },
  { fnm: "4-F-8", name: "Levonorgestrel + Etinilestradioli (Píl. de Emerg.) 250 µg + 50 µg" },
  { fnm: "4-F-9", name: "Dispositivo Intra-Uterino (DIU) Copper-T CU 380" },
  { fnm: "-", name: "Etonogestrel 60 mg implante" },
  { fnm: "-", name: "Preservativo Masculino" },
  { fnm: "-", name: "Preservativo Feminino" },


  { fnm: "4-J-3", name: "Sildenafil 50 mg Comp." },
  { fnm: "5-A-1", name: "Aminofilina 100 mg Comp." },
  { fnm: "5-A-2", name: "Aminofilina 240 mg/10 ml Inj." },
  { fnm: "5-A-8", name: "Salbutamol 100 µg/inalação Aerossol pressurizado" },
  { fnm: "5-A-9", name: "Salbutamol 2 mg Comp." },
  { fnm: "5-A-10", name: "Salbutamol 500 µg/1 ml Inj." },
  { fnm: "5-A-11", name: "Salbutamol 5 mg/mL Sol. nebulizável" },
  { fnm: "5-A-12", name: "Salbutamol 2 mg/5 ml Xpe." },
  { fnm: "5-A-14", name: "Teofilina 250 mg Comp. de acção prolongada" },
  { fnm: "6-A-1", name: "Ácido Fólico (Vitamina B9) 5 mg Comp." },
  { fnm: "6-A-4", name: "Gluconato de Ferro 30 mg/5 ml Xpe." },
  { fnm: "6-A-5", name: "Hidroxicobalamina (Vitamina B12) 1 mg/mL Inj." },
  { fnm: "6-A-6", name: "Sulfato Ferroso 200 mg Comp." },
  { fnm: "6-A-7", name: "Sulfato Ferroso e Ácido Fólico 91 mg Comp." },
  { fnm: "-", name: "Sulfato Ferroso e Ácido Fólico 301 mg Comp." },
  { fnm: "6-E-1", name: "Ácido Acetilsalicílico 100 mg Comp." },
  { fnm: "6-F-7", name: "Fitomenadiona (Vitamina K1) 2 mg/0,2 ml Inj." },
  { fnm: "6-F-8", name: "Fitomenadiona (Vitamina K1) 10 mg/mL Inj." },
  { fnm: "7-A-1", name: "Acetil Salicilato de Lisina 900 mg/5 ml Inj." },
  { fnm: "7-A-2", name: "Ácido Acetilsalicílico 500 mg Comp." },
  { fnm: "7-A-3", name: "Paracetamol 500 mg Comp." },
  { fnm: "7-A-4", name: "Paracetamol 1 g/100 ml Inj." },
  { fnm: "7-A-6", name: "Paracetamol 120 mg/5 ml Susp." },
  { fnm: "7-B-1", name: "Codeína 30 mg Comp." },
  { fnm: "7-B-2", name: "Codeína 25 mg/5 ml Xpe." },
  { fnm: "7-B-3", name: "Dextropropoxifeno 65 mg Cáps." },
  { fnm: "7-B-6", name: "Morfina 10 mg/mL Inj." },
  { fnm: "7-B-7", name: "Morfina 5 mg/5 ml Sol. oral" },
  { fnm: "7-B-8", name: "Petidina 100 mg/2 ml Inj." },

  { fnm: "7-B-9", name: "Tramadol 50 mg Cáps." },
  { fnm: "7-B-10", name: "Tramadol 100 mg Comp. de Libertação lenta" },
  { fnm: "7-B-11", name: "Tramadol 100 mg/2 ml Inj." },
  { fnm: "7-C-1", name: "Ergotamina e Cafeína 101 mg Comp." },
  { fnm: "7-D-1", name: "Carbamazepina 200 mg Comp." },
  { fnm: "7-D-4", name: "Fenitoína 100 mg Comp." },
  { fnm: "7-D-5", name: "Fenitoína 250 mg/5 ml Inj." },
  { fnm: "7-D-6", name: "Fenobarbital 15 mg Comp." },
  { fnm: "7-D-7", name: "Fenobarbital 100 mg Comp." },
  { fnm: "7-D-8", name: "Fenobarbital 200 mg/2 ml Inj." },
  { fnm: "7-D-13", name: "Valproato de Sódio 200 mg Comp." },
  { fnm: "7-D-14", name: "Valproato de Sódio 200 mg/5 ml Xpe." },
  { fnm: "7-E-2", name: "Meclizina 25 mg Comp." },
  { fnm: "7-F-1", name: "Biperideno 2 mg Comp." },
  { fnm: "7-F-2", name: "Biperideno 5 mg/mL Inj." },
  { fnm: "7-G-1", name: "Amitriptilina 10 mg Comp." },
  { fnm: "7-G-2", name: "Amitriptilina 25 mg Comp." },
  { fnm: "7-I-1", name: "Alprazolam 0,5 mg Comp." },
  { fnm: "7-I-2", name: "Bromazepam 3 mg Comp." },
  { fnm: "7-I-4", name: "Clordiazepóxido 10 mg Comp." },
  { fnm: "7-I-5", name: "Diazepam 2 mg Comp." },
  { fnm: "7-I-6", name: "Diazepam 10 mg Comp." },
  { fnm: "7-I-7", name: "Diazepam 10 mg/2 ml Inj." },
  { fnm: "7-J-1", name: "Clorpromazina 25 mg Comp." },
  { fnm: "7-J-2", name: "Clorpromazina 100 mg Comp." },
  { fnm: "7-J-3", name: "Clorpromazina 25 mg/2 ml Inj." },
  { fnm: "7-J-6", name: "Haloperidol 5 mg Comp." },

  { fnm: "7-J-6", name: "Haloperidol 5 mg/1 ml Inj." },
  { fnm: "8-A-1", name: "Fenoximetilpenicilina 500 mg Comp." },
  { fnm: "8-A-2", name: "Fenoximetilpenicilina 250 mg/5 ml Susp." },
  { fnm: "8-A-4", name: "Penicilina Benzatínica 2 400 000 U.I Inj." },
  { fnm: "8-A-5", name: "Penicilina G Cristalina 10 000 000 U.I Inj." },
  { fnm: "8-A-6", name: "Penicilina Procaína 3 000 000 U.I Inj." },
  { fnm: "8-A-7", name: "Amoxicilina 500 mg Cáps." },
  { fnm: "8-A-8", name: "Amoxicilina 250 mg/5 ml Susp." },
  { fnm: "8-A-9", name: "Ampicilina 500 mg Inj." },
  { fnm: "8-A-10", name: "Amoxicilina e Ácido Clavulânico 375 mg Comp." },
  { fnm: "8-A-11", name: "Amoxicilina e Ácido Clavulânico 625 mg Comp." },
  { fnm: "8-A-12", name: "Amoxicilina e Ácido Clavulânico 312,5 mg/5 ml" },
  { fnm: "8-A-13", name: "Flucloxacilina 250 mg Cáps." },
  { fnm: "8-A-14", name: "Flucloxacilina 500 mg Inj." },
  { fnm: "8-A-15", name: "Flucloxacilina 125 mg/5 ml Susp." },
  { fnm: "8-B-4", name: "Cefixima 200 mg Comp." },
  { fnm: "8-B-5", name: "Cefixima 100 mg/5 ml Susp." },
  { fnm: "8-B-8", name: "Ceftriaxona 1 g/4 ml Inj." },
  { fnm: "8-D-3", name: "Gentamicina 80 mg/2 ml Inj." },
  { fnm: "8-D-4", name: "Gentamicina 20 mg/2 ml Inj." },
  { fnm: "8-D-5", name: "Kanamicina 1 g/3 ml Inj." },
  { fnm: "8-E-1", name: "Clindamicina 150 mg Cáps." },
  { fnm: "8-E-2", name: "Clindamicina 150 mg/mL Inj." },
  { fnm: "8-F-1", name: "Azitromicina 500 mg Comp." },
  { fnm: "8-F-2", name: "Azitromicina 200 mg/5 ml Susp." },
  { fnm: "8-F-6", name: "Eritromicina 500 mg Comp." },
  { fnm: "8-F-7", name: "Eritromicina 50 mg/mL Inj." },
  { fnm: "8-F-8", name: "Eritromicina 250 mg/5 ml Susp." },
  { fnm: "8-G-1", name: "Doxiciclina 100 mg Cáps." },

  { fnm: "8-G-3", name: "Tetraciclina 500 mg Cáps." },
  { fnm: "8-H-3", name: "Ciprofloxacina 500 mg Comp." },
  { fnm: "8-H-4", name: "Ciprofloxacina 2 mg/mL Inj." },
  { fnm: "8-I-1", name: "Cotrimoxazol 480 mg Comp." },
  { fnm: "8-I-2", name: "Cotrimoxazol 480 mg/5 ml Inj." },
  { fnm: "8-I-3", name: "Cotrimoxazol 240 mg/5 ml Susp." },
  { fnm: "8-K-1", name: "Cloranfenicol 250 mg Cáps." },
  { fnm: "8-K-2", name: "Cloranfenicol 1 g/10 ml Inj." },
  { fnm: "8-K-3", name: "Cloranfenicol 250 mg/5 ml Susp." },
  { fnm: "8-K-4", name: "Metronidazol 250 mg Comp." },
  { fnm: "8-K-5", name: "Metronidazol 500 mg/100 ml Inj." },
  { fnm: "8-K-7", name: "Metronidazol 200 mg/5 ml Susp." },
  { fnm: "8-K-8", name: "Nitrofurantoína 50 mg Comp." },
  { fnm: "8-K-9", name: "Nitrofurantoína 25 mg/5 ml Susp." },
  { fnm: "8-L-1", name: "Estreptomicina 1 g/5 ml Inj." },
  { fnm: "8-L-3", name: "Isoniazida 300 mg Comp." },
  { fnm: "8-L-4", name: "Isoniazida 100 mg Comp." },
  { fnm: "8-N-1", name: "Albendazol 400 mg Comp." },
  { fnm: "8-N-3", name: "Ivermectina 6 mg Comp." },
  { fnm: "8-N-4", name: "Mebendazol 100 mg Comp." },
  { fnm: "8-N-6", name: "Praziquantel 600 mg Comp." },
  { fnm: "8-N-7", name: "Tiabendazol 30 g Pomada" },
  { fnm: "8-O-5", name: "Arteméter e Lumefantrina 140 mg Comp. (6 × 1)" },
  { fnm: "8-O-5", name: "Arteméter e Lumefantrina 140 mg Comp. (6 × 2)" },
  { fnm: "8-O-5", name: "Arteméter e Lumefantrina 140 mg Comp. (6 × 3)" },
  { fnm: "8-O-5", name: "Arteméter e Lumefantrina 140 mg Comp. (6 × 4)" },
  { fnm: "-", name: "Artesunato 60 mg/6 ml Inj." },

  { fnm: "8-O-10", name: "Quinina 100 mg Comp." },
  { fnm: "8-O-11", name: "Quinina 300 mg Comp." },
  { fnm: "8-O-12", name: "Quinina 600 mg/2 ml Inj." },
  { fnm: "8-O-13", name: "Sulfadoxina e Pirimetamina (Fanzidar) 525 mg Comp." },
  { fnm: "8-O-15", name: "Artesunato e Amodiaquina 370 mg Comp." },
  { fnm: "8-Q-2", name: "Fluconazol 200 mg Comp." },
  { fnm: "8-Q-5", name: "Griseofulvina 500 mg Comp." },
  { fnm: "8-Q-6", name: "Ketoconazol 200 mg Comp." },
  { fnm: "8-Q-7", name: "Nistatina 100 000 U.I/mL Susp." },
  { fnm: "8-R-1", name: "Aciclovir 400 mg Comp." },
  { fnm: "10-A-1", name: "Amilorido 5 mg Comp." },
  { fnm: "10-A-2", name: "Espironolactona 5 mg Comp." },
  { fnm: "10-A-3", name: "Furosemida 40 mg Comp." },
  { fnm: "10-A-4", name: "Furosemida 20 mg/2 ml Inj." },
  { fnm: "10-A-6", name: "Hidroclorotiazida 50 mg Comp." },
  { fnm: "-", name: "Hidroclorotiazida 25 mg Comp." },
  { fnm: "10-A-7", name: "Hidroclorotiazida e Amilorido 55 mg Comp." },
  { fnm: "10-A-8", name: "Manitol a 20% 12,5 g/50 ml Inj." },
  { fnm: "11-A-1", name: "Bicarbonato de Sódio a 8,4% 1 mEq/mL Inj." },
  { fnm: "11-A-9", name: "Cloreto de Sódio a 0,9% Inj." },
  { fnm: "11-A-15", name: "Dextrose a 5% Inj." },
  { fnm: "11-A-19", name: "Lactato de Ringer/Solução de Hartmann Inj." },
  { fnm: "11-A-22", name: "Resomal Pó em Pct." },
  { fnm: "11-A-23", name: "Sais de Reidratação Oral (SRO) Pó em Pct." },
  { fnm: "12-B-3", name: "Dextrose a 10% Inj." },
  { fnm: "12-B-6", name: "Dextrose a 50% Inj." },
  { fnm: "12-D-1", name: "Ácido Ascórbico (Vitamina C) 100 mg Comp." },
  { fnm: "12-D-4", name: "Axeroftol (Vitamina A) 200 000 U.I Cáps. de Sol. oleosa" },
  { fnm: "12-D-5", name: "Axeroftol (Vitamina A) 100 000 U.I/mL Sol. oral (oleosa)" },

  { fnm: "12-D-6", name: "Colecalciferol (Vitamina D-3) 600 000 U.I/mL Amp. bebível" },
  { fnm: "12-D-8", name: "Complexo B Comp." },
  { fnm: "12-D-10", name: "Multivitaminas Comp." },
  { fnm: "12-D-11", name: "Multivitaminas Xpe." },
  { fnm: "12-D-12", name: "Nicotinamida (Vitamina PP) 100 mg Comp." },
  { fnm: "12-D-14", name: "Piridoxina (Vitamina B6) 50 mg Comp." },
  { fnm: "12-D-16", name: "Tiamina (Vitamina B1) 100 mg Comp." },
  { fnm: "12-D-17", name: "Tiamina (Vitamina B1) 100 mg/2 ml Inj." },
  { fnm: "13-A-1", name: "Adrenalina 1 mg/mL Inj." },
  { fnm: "13-A-2", name: "Clorfeniramina 4 mg Comp." },
  { fnm: "13-A-3", name: "Clorfeniramina 2 mg/5 ml Xpe." },
  { fnm: "13-A-4", name: "Difenidramina 50 mg/5 ml Inj." },
  { fnm: "13-A-8", name: "Prometazina 10 mg Comp." },
  { fnm: "13-A-10", name: "Prometazina 50 mg/2 ml Inj." },
  { fnm: "14-A-1", name: "Diclofenac 50 mg Comp." },
  { fnm: "14-A-2", name: "Diclofenac 75 mg/3 ml Inj." },
  { fnm: "14-A-3", name: "Ibuprofeno 200 mg Comp." },
  { fnm: "14-A-3", name: "Ibuprofeno 400 mg Comp." },
  { fnm: "14-A-4", name: "Ibuprofeno 100 mg/5 ml Susp." },
  { fnm: "14-A-5", name: "Indometacina 25 mg Comp." },
  { fnm: "14-B-1", name: "Alopurinol 100 mg Comp." },
  { fnm: "14-B-2", name: "Colchina 0,5 mg Comp." },
  { fnm: "14-C-1", name: "Mentol e Salicilato de Metilo 20 g Pomada" },
  { fnm: "15-B-1", name: "Betametasona 30 g Creme cutâneo a 0,1%" },
  { fnm: "15-B-11", name: "Hidrocortisona 30 g Creme cutâneo a 1%" },
  { fnm: "15-C-1", name: "Aciclovir 30 g Creme cutâneo a 5%" },
  { fnm: "15-C-2", name: "Ácido Fusídico 15 g Creme a 2%" },

  { fnm: "15-C-3", name: "Ácido Salicílico e Ácido Benzóico 100 g Pomada" },
  { fnm: "15-C-5", name: "Bacitracina 15 g Pomada a 1%" },
  { fnm: "15-C-8", name: "Clotrimazol 30 g Creme cutâneo a 1%" },
  { fnm: "15-C-15", name: "Hexacloreto de Benzeno 600 mg/60 ml Loção" },
  { fnm: "15-C-17", name: "IodoPovidona Sol. - Fr. 100 ml" },
  { fnm: "15-C-18", name: "Ketoconazol 30 g Creme cutâneo a 2%" },
  { fnm: "15-C-20", name: "Miconazol 30 g Gel a 2%" },
  { fnm: "15-C-21", name: "Miconazol 10 mg Mucoadesivos" },
  { fnm: "15-D-1", name: "Ácido Salicílico 100 g Pomada a 5%" },
  { fnm: "16-A-2", name: "Cloranfenicol Gotas auriculares a 5%" },
  { fnm: "16-A-4", name: "Fenazona e Procaína 6 g Gotas auriculares" },
  { fnm: "17-C-2", name: "Ciprofloxacina Colírio a 0,3%" },
  { fnm: "17-C-3", name: "Cloranfenicol Colírio a 0,5%" },
  { fnm: "17-C-4", name: "Cloranfenicol 4 g Pomada oftálmica a 1%" },
  { fnm: "17-C-5", name: "Gentamicina Colírio a 0,3%" },
  { fnm: "17-C-7", name: "Tetraciclina 4 g Pomada oftálmica a 1%" },
  { fnm: "17-D-3", name: "Prednisolona colírio a 1%" },
  { fnm: "18-C-4", name: "Cloreto de Etilo 100 ml de líquido volátil Spray" },
  { fnm: "18-C-5", name: "Lidocaína a 2% 20 mg/mL Inj." },
  { fnm: "18-C-8", name: "Lidocaína 2 g/100 ml Gel" },
  { fnm: "18-C-9", name: "Lidocaína a 10% 10 mg/jacto Spray" },
  { fnm: "19-A-3", name: "Imunoglobulina Anti-Rábica 1000 U.I/5 ml Inj." },
  { fnm: "19-A-6", name: "Soro Anti-Ofídico, polivalente 10 ml Inj." },
  { fnm: "19-B-6", name: "Vacina Anti-Rábica 1 ml Inj." },
  { fnm: "20-A-1", name: "Água Oxigenada a 10 volumes Sol. a 3% - Fr. 500 ml" },
  { fnm: "20-A-3", name: "Álcool a 70% - Fr. 1000 ml" },

  { fnm: "20-A-10", name: "Hipoclorito de Sódio Sol. - Fr. 1000 ml" },
  { fnm: "20-A-15", name: "Sulfadiazina de Prata Creme a 1%" },
  { fnm: "21-A-4", name: "Carvão Activado Pó - Pacote de 300 g" },
  { fnm: "22-A-3", name: "Tuberculina Purificada 2 TU 1,5 ml Inj." },
  { fnm: "-", name: "ATPU (PlumpyNut) 500 kcal Pasta em Saqueta" },
  { fnm: "-", name: "ASPU (PlumpySup) 500 kcal Pasta em Saqueta" },
  { fnm: "-", name: "MAE (CSB Plus/Super Cereal) 1.5 kg Farinha em Pacote" },
  { fnm: "-", name: "MAE (CSB Plus/Super Cereal) 10 kg Farinha em Saquinho" },
  { fnm: "-", name: "Seringas 2.5 ml" },
  { fnm: "-", name: "Seringas 3 ml" },
  { fnm: "-", name: "Seringas 5 ml" },
  { fnm: "-", name: "Seringas 10 ml" },
  { fnm: "-", name: "Seringas 20 ml" },
  { fnm: "-", name: "Luvas Cirúrgicas Tamanho 6" },
  { fnm: "-", name: "Luvas Cirúrgicas Tamanho 6.5" },
  { fnm: "-", name: "Luvas Cirúrgicas Tamanho 7" },
  { fnm: "-", name: "Luvas Cirúrgicas Tamanho 7.5" },
  { fnm: "-", name: "Luvas Cirúrgicas Tamanho 8" },
  { fnm: "-", name: "Luvas Cirúrgicas Tamanho 8.5" },
  { fnm: "-", name: "Luvas Ginecológicas Tamanho 6" },
  { fnm: "-", name: "Luvas Ginecológicas Tamanho 6.5" },
  { fnm: "-", name: "Luvas Ginecológicas Tamanho 7" },
  { fnm: "-", name: "Luvas Ginecológicas Tamanho 7.5" },
  { fnm: "-", name: "Luvas Ginecológicas Tamanho 8" },
  { fnm: "-", name: "Luvas Ginecológicas Tamanho 8.5" },
  { fnm: "-", name: "Luvas de Procedimento Tamanho S (Pequeno)" },
  
  { fnm: "-", name: "Luvas de Procedimento Tamanho M (Médio)" },
  { fnm: "-", name: "Luvas de Procedimento Tamanho L (Grande)" },
  { fnm: "-", name: "Luvas de Lavandaria" },
  { fnm: "-", name: "Luvas de Limpeza" },
  { fnm: "-", name: "Máscaras cirúrgicas" },
  { fnm: "-", name: "Máscaras N95" },
  { fnm: "-", name: "Barrete" },
  { fnm: "-", name: "Aventais Plásticos" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" },
  { fnm: "FNM", name: "" }
];